version: "3"

services:
  web:
    image: node:18
    container_name: node-web
    volumes:
     - ./:/workspace
    ports:
     - 80:1234
    environment:
     - TZ=Asia/Seoul
    command: /workspace/script/setup.sh